metadata.format.version = "1.1"

[versions]

velocity = "3.4.0-SNAPSHOT"
kotlin="2.3.0"
paper = "1.20.1-R0.1-SNAPSHOT"
runtask = "3.0.2"
plugin-yml = "0.6.0"
blossom = "2.2.0"
sponge-api = "14.0.0"
sponge-gradle = "2.3.0"
shadow = "9.3.0"
log4j = "2.25.2"
slf4j = "2.0.17"

[libraries]

#Gradle dependencies
plugin-shadow = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }
plugin-kotlin =  { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

velocity = { group  = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
paper  = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
viaproxy = { module = "net.raphimc:ViaProxy", version = "3.4.7" }

log4j = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

[plugins]

runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }

pluginyml-paper = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
sponge-gradle = { id = "org.spongepowered.gradle.plugin", version.ref = "sponge-gradle" }

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }
